{% set name = "bats-core" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bats-core/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 91c49b1fe6f0656c46491929ed728f8dfa9a96df0cce294963e8c6082bff87a2

build:
  number: 0

test:
  commands:
    - bash -c 'bats --help'
    - bash -c 'test "$(bats --version)" = "Bats {{ version }}"'

about:
  home: http://github.com/bats-core/bats-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'BATS: Bash Automated Testing System'

  description: |
    Bats is a TAP-compliant testing framework for Bash. It provides a simple way to
    verify that the UNIX programs you write behave as expected.
  dev_url: https://github.com/bats-core/bats-core

extra:
  recipe-maintainers:
    - sodre
