travis:
  secure:
    BINSTAR_TOKEN: unn0MpGCaZC5KpMlXscb/33ts9ADq/KRcjns8X3mJaVt/VbyEGPtUUqmBvYLdvz4P4Fmv9Fcah2Fj8xE/Svdnc6Hf3XK0FH/93zkeX4v6PDAwK/Vdim+km1bqjcN1r08+JkVw0lTBKX1X78fpq/EaakrzPoip2tBQOqxwHgjjFav3N7LMmbSh95olsNvc2iqoWOVekoBIv2/W9bmFjZrlaaZoghLXUC/HVaaJRNEf1m75QtwTYz/YAc+fscMDtJjHksO/OwWOIlfGbMlwf44wUQVq5v30Dl4ldD9zwdfJ3uJ1G7SDr7h2h79LebJFDWP0qTilvftcS10OfholGVfBOZ5yC+mpguJ0u6WiZNAKEX86qAB8E8CkigxI4vZOIKk9eLo7MaK33nHIXdOknLcQYYc3OY4tGuQnppCzmK0V9w2+rLNqdGDj+K4/168RgKa6jAUqASAzfu/0areZaDjGDiZvVWVnvkJr8BuC723vZPs2bXeh6JqOQpeVOiAmqwr8rb0QgG1ncIZ5MdGQpNfIjm9C4/tLPxLNInyrMaxSpfJ8PW+O0q1JFTbquAn8cvRXRDbkFxvPBzVv1yx7dSPvpof5p5drLADk7Bx2SvodW4ViqRdT5yc68839tACZARC7IItsT448QDyMfoKoYKW933wqVWkcn6rcaGL3sB5bbk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
