travis:
  secure:
    BINSTAR_TOKEN: nTIeVmGOctXepeiUPy3IDTK1UB5PcMssIsXvjkYUsXcYIJT3nKg/T2dElUvqwa+xu+AYmXuOrbR6wrZm2542i+R8OeWGdlUZHORs40qcyq2XMcMZurCnSKaKn9yiGHE8iebdqLwdzOOt0z0GekJddKmXXDaoqTh0gt2/Lk1ubvxyf+tB7eBzcUp9aDo2zIFYvmJgMb3euZ8IS9G9if26aqaVvmVifZ2bcoI2i8KS1wb53VZs+hnOBy+H4O+2j12pfm2WrKSeE4ACfO0alqcLBDdsyeFqLplrTr7wQWCxoOrS7gK1h1J0JSeYAF/0RMG7d0QR3HTXkopbqJDJ1iSjdPxHGeOmOGeFGes4QQP/Pupg2n6DXtYE/jXtpBN7mL0d038Kb7h/Kz9jNW9nUl2lrnEdX0PHj2FPAA8/vDEjrMFBlEiS34hcfQ49pEe3/U/DIJEDlyzCgWoB9rnLUOsj78NG4mKGl+qNPMijw0BhqrgdnKnY3WnK0nDFJLw7HT64sIFY5A3OX0uKBy5/hQr3RZP2pAYxMjLb8vO6JtmvFlAcWEUHONHhcw/cnVFUmMx4hv7BD9A0sMXVamTDLb2OBh8poIzOpbWE5VP+vi2EsPVzG5rN99uYUi8K+BwIgePfuRikuzdboYiAeylguRr8fJVWqwJGZiw95Bn/8jLOkNg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
